version: 2
updates:
  # Atualizações para dependências do Gradle
  - package-ecosystem: "gradle"
    directory: "/" # Local do arquivo build.gradle ou settings.gradle
    schedule:
      interval: "weekly"

  # Atualizações para versão do Java
  - package-ecosystem: "github-actions"
    directory: "/" # Local do workflow do GitHub Actions
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"

  # Atualizações para dependências do PaperMC (se gerenciadas via Gradle)
  - package-ecosystem: "gradle"
    directory: "/" # PaperMC configurado no build.gradle
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.papermc.paper"
        versions:
          - "<1.23" # Ignora versões abaixo da mínima suportada
