version: 2
updates:
  # Atualizações para todas as dependências do Gradle, incluindo PaperMC
  - package-ecosystem: "gradle"
    directory: "/" # Local do arquivo build.gradle ou settings.gradle
    schedule:
      interval: "daily"

  # Atualizações para versão do Java nos workflows de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Local do workflow do GitHub Actions
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
